---
- name: Obtener versi贸n de Windows
  hosts: tu_host_windows
  gather_facts: yes
  tasks:
    - name: Ejecutar comando de versi贸n de Windows
      win_shell: |
        $version = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name "ReleaseId").ReleaseId
        Write-Host "La versi贸n de Windows es: $version"
      register: version_output

    - name: Mostrar versi贸n de Windows
      debug:
        var: version_output.stdout_lines
